FROM golang:1.10

# copy over all files to /home/source/
WORKDIR /home/source/
COPY . /home/source/

# install python + dependencies + nodejs
RUN apt update
RUN apt install python3 -y
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt install -y nodejs
RUN apt install -y build-essential
RUN apt install -y python3-pip
RUN pip3 install numpy
RUN pip3 install pandas

# create /home/run/ directory to run terminal nodejs project from
RUN mkdir /home/run/
COPY ./terminal-server/ /home/run/terminal-server/

# install required NPM packages for term.js
WORKDIR /home/run/terminal-server/
RUN npm install

# create work directory
RUN mkdir /home/user/

# set working directory to source to install go dependencies
WORKDIR /home/source/

RUN go get -d -v ./...

# expose ports
EXPOSE 8080
EXPOSE 3000

CMD ["bash","run-go-term.sh"]